[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = [
  "python3 -m ensurepip --default-pip",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "python3 dashboard/app.py"
